# Travis CI configuration file.
sudo: false

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Cache composer for faster build
cache:
  directories:
    # Cache directory for older Composer versions.
    - $HOME/.composer/cache/files
    # Cache directory for more recent Composer versions.
    - $HOME/.cache/composer/files

# Declare versions of PHP to use. Use one decimal max.
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
    fast_finish: true

    include:
        - php: "5.6"
        - php: "7.0"
        - php: "7.1"
        - php: "7.2"
        - php: "7.3"
          # Use this to prepare your build for testing.
          # e.g. copy database configurations, environment variables, etc.
          # Failures in this section will result in build status 'errored'.
          before_install:
            # disable Xdebug to speed up building process
            - phpenv config-rm xdebug.ini || echo 'No xdebug config.'
            # Install PHP packages.
            - composer install --ansi --prefer-dist --no-suggest
            # Install ESLint shareable config for WordPress.
            # @link https://github.com/WordPress-Coding-Standards/eslint-config-wordpress
            - npm install eslint eslint-config-wordpress
          # Run test script commands.
          # Default is specific to project language.
          # All commands must exit with code 0 on success. Anything else is considered failure.
          script:
            - ./vendor/bin/phpcs

before_script:
  # Install PHP packages.
  - composer install --ansi --prefer-dist --no-suggest
script:
  # Search for PHP syntax errors.
  - ./vendor/bin/parallel-lint --blame --exclude vendor/ .

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
    email: false